// Field schema config for the generic content editor, per content kind.
export const KIND_META = {
  articles: { label: "Historia", title: "Historias de la comunidad", route: "/historias", categoriesKey: "article_categories", aiTarget: "body" },
  resources: { label: "Recurso", title: "Recursos", route: "/recursos", categoriesKey: "resource_categories", aiTarget: "what_offers" },
  "oregon-info": { label: "Explicación", title: "Oregon Te Informa", route: "/oregon-te-informa", categoriesKey: "oregon_info_categories", aiTarget: "body" },
  places: { label: "Lugar", title: "Conoce Oregon", route: "/conoce-oregon", categoriesKey: "place_categories", aiTarget: "description" },
  sponsors: { label: "Patrocinador", title: "Patrocinadores", route: "/aliados", categoriesKey: "article_categories", aiTarget: "summary" },
};

// type: text | textarea | number | select | selectConfig | checkbox | image | gallery | tags | sources
export const SCHEMAS = {
  articles: [
    { name: "title", label: "Titular", type: "text", span: 2, required: true },
    { name: "subtitle", label: "Subtítulo", type: "text", span: 2 },
    { name: "summary", label: "Resumen / Extracto", type: "textarea", span: 2 },
    { name: "category", label: "Categoría", type: "selectConfig", cfg: "article_categories" },
    { name: "content_type", label: "Tipo de contenido", type: "selectConfig", cfg: "article_types" },
    { name: "city", label: "Ciudad", type: "selectConfig", cfg: "cities", optional: true },
    { name: "county", label: "Condado", type: "selectConfig", cfg: "counties", optional: true },
    { name: "reading_time", label: "Tiempo de lectura (min)", type: "number" },
    { name: "author", label: "Autor", type: "text" },
    { name: "featured_image", label: "Imagen destacada", type: "image", span: 2 },
    { name: "body", label: "Contenido", type: "textarea", span: 2, big: true, ai: true },
    { name: "tags", label: "Tags (separados por coma)", type: "tags", span: 2 },
    { name: "featured", label: "Destacar en portada", type: "checkbox" },
    { name: "used_ai", label: "Usó AI en la creación", type: "checkbox" },
    { name: "seo_title", label: "SEO Title", type: "text", span: 2, seo: true },
    { name: "seo_description", label: "Meta description", type: "textarea", span: 2, seo: true },
    { name: "sources", label: "Fuentes", type: "sources", span: 2 },
  ],
  resources: [
    { name: "title", label: "Título", type: "text", span: 2, required: true },
    { name: "category", label: "Categoría", type: "selectConfig", cfg: "resource_categories" },
    { name: "organization", label: "Organización", type: "text" },
    { name: "program_type", label: "Tipo de programa", type: "text" },
    { name: "summary", label: "Descripción corta", type: "textarea", span: 2 },
    { name: "what_offers", label: "Qué ofrece", type: "textarea", span: 2, ai: true },
    { name: "who_helps", label: "A quién ayuda", type: "textarea", span: 2 },
    { name: "requirements", label: "Requisitos", type: "textarea", span: 2 },
    { name: "documents", label: "Documentos necesarios", type: "textarea", span: 2 },
    { name: "how_to_apply", label: "Cómo solicitar", type: "textarea", span: 2 },
    { name: "phone", label: "Teléfono", type: "text" },
    { name: "email", label: "Email", type: "text" },
    { name: "website", label: "Website", type: "text" },
    { name: "address", label: "Dirección", type: "text" },
    { name: "city", label: "Ciudad", type: "selectConfig", cfg: "cities", optional: true },
    { name: "county", label: "Condado", type: "selectConfig", cfg: "counties", optional: true },
    { name: "state", label: "Estado", type: "text" },
    { name: "languages", label: "Idiomas disponibles", type: "text" },
    { name: "last_verified", label: "Última verificación (fecha)", type: "text" },
    { name: "official_source", label: "Fuente oficial (URL)", type: "text", span: 2 },
    { name: "featured_image", label: "Imagen", type: "image", span: 2 },
    { name: "sources", label: "Fuentes", type: "sources", span: 2 },
  ],
  "oregon-info": [
    { name: "title", label: "Título", type: "text", span: 2, required: true },
    { name: "category", label: "Categoría", type: "selectConfig", cfg: "oregon_info_categories" },
    { name: "used_ai", label: "Usó AI", type: "checkbox" },
    { name: "summary", label: "Resumen corto", type: "textarea", span: 2 },
    { name: "que_cambio", label: "¿Qué cambió?", type: "textarea", span: 2, ai: true },
    { name: "a_quien_afecta", label: "¿A quién afecta?", type: "textarea", span: 2 },
    { name: "cuando_entra_en_vigor", label: "¿Cuándo entra en vigor?", type: "text", span: 2 },
    { name: "que_necesitas_hacer", label: "¿Qué necesitas hacer?", type: "textarea", span: 2 },
    { name: "official_source", label: "Fuente oficial (URL)", type: "text", span: 2 },
    { name: "body", label: "Contenido adicional", type: "textarea", span: 2, big: true },
    { name: "featured_image", label: "Imagen", type: "image", span: 2 },
    { name: "sources", label: "Fuentes", type: "sources", span: 2 },
  ],
  places: [
    { name: "title", label: "Nombre del lugar", type: "text", span: 2, required: true },
    { name: "category", label: "Categoría", type: "selectConfig", cfg: "place_categories" },
    { name: "city", label: "Ciudad", type: "selectConfig", cfg: "cities", optional: true },
    { name: "county", label: "Condado", type: "selectConfig", cfg: "counties", optional: true },
    { name: "summary", label: "Resumen", type: "textarea", span: 2 },
    { name: "description", label: "Descripción", type: "textarea", span: 2, big: true, ai: true },
    { name: "history", label: "Historia", type: "textarea", span: 2 },
    { name: "location", label: "Ubicación (dirección)", type: "text", span: 2 },
    { name: "hours", label: "Horarios", type: "text" },
    { name: "cost", label: "Costo", type: "text" },
    { name: "accessibility", label: "Accesibilidad", type: "text" },
    { name: "parking", label: "Estacionamiento", type: "text" },
    { name: "rules", label: "Reglas", type: "textarea", span: 2 },
    { name: "services", label: "Servicios disponibles", type: "textarea", span: 2 },
    { name: "official_source", label: "Sitio oficial (URL)", type: "text", span: 2 },
    { name: "featured_image", label: "Imagen principal", type: "image", span: 2 },
    { name: "gallery", label: "Galería", type: "gallery", span: 2 },
    { name: "sources", label: "Fuentes", type: "sources", span: 2 },
  ],
  sponsors: [
    { name: "title", label: "Nombre del patrocinador", type: "text", span: 2, required: true },
    { name: "tier", label: "Nivel", type: "select", options: [
      { value: "oro", label: "Oro" }, { value: "plata", label: "Plata" }, { value: "bronce", label: "Bronce" },
    ] },
    { name: "active", label: "Activo", type: "checkbox" },
    { name: "logo", label: "Logo", type: "image", span: 2 },
    { name: "summary", label: "Descripción corta", type: "textarea", span: 2 },
    { name: "website", label: "Sitio web (URL)", type: "text", span: 2 },
    { name: "phone", label: "Teléfono (para botón Llamar)", type: "text" },
    { name: "address", label: "Dirección (para botón Cómo llegar)", type: "text" },
    { name: "order", label: "Orden (menor = primero)", type: "number" },
    { name: "start_date", label: "Fecha inicio (YYYY-MM-DD, opcional)", type: "text" },
    { name: "end_date", label: "Fecha fin (YYYY-MM-DD, opcional)", type: "text" },
  ],
};
